
package com.capgemini.lionsii.aeat.ssii.fact.ws.suministrofactemitidas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "siiService", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", wsdlLocation = "http://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_07/SuministroFactEmitidas.wsdl")
public class SiiService
    extends Service
{

    private final static URL SIISERVICE_WSDL_LOCATION;
    private final static WebServiceException SIISERVICE_EXCEPTION;
    private final static QName SIISERVICE_QNAME = new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "siiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_07/SuministroFactEmitidas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIISERVICE_WSDL_LOCATION = url;
        SIISERVICE_EXCEPTION = e;
    }

    public SiiService() {
        super(__getWsdlLocation(), SIISERVICE_QNAME);
    }

    public SiiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIISERVICE_QNAME, features);
    }

    public SiiService(URL wsdlLocation) {
        super(wsdlLocation, SIISERVICE_QNAME);
    }

    public SiiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIISERVICE_QNAME, features);
    }

    public SiiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiiSOAP
     */
    @WebEndpoint(name = "SuministroFactEmitidasPruebas")
    public SiiSOAP getSuministroFactEmitidasPruebas() {
        return super.getPort(new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "SuministroFactEmitidasPruebas"), SiiSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiiSOAP
     */
    @WebEndpoint(name = "SuministroFactEmitidasPruebas")
    public SiiSOAP getSuministroFactEmitidasPruebas(WebServiceFeature... features) {
        return super.getPort(new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "SuministroFactEmitidasPruebas"), SiiSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIISERVICE_EXCEPTION!= null) {
            throw SIISERVICE_EXCEPTION;
        }
        return SIISERVICE_WSDL_LOCATION;
    }

}
